# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.16

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3.9 -m venv testenv
            source testenv/bin/activate          
            pip install -r requirements.txt  
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source testenv/bin/activate
            python -m unittest